# Generated by Django 4.2.7 on 2023-11-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=20240101, max_length=10, verbose_name='Новое поле'),
            preserve_default=False,
        ),
    ]
