# Generated by Django 4.2.7 on 2023-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_change',
            field=models.DateField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_create',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
