# Generated by Django 4.2.7 on 2023-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_data_change_alter_product_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/', verbose_name='Изображение'),
        ),
    ]
