# Generated by Django 4.2.7 on 2024-01-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('reset_is_published', 'отмена публикации продукта'), ('change_category', 'изменение категории у продукта'), ('change_description', 'изменение описания продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
